// <auto-generated />
using System;
using Assement.Database_Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assement.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperenceYear")
                        .HasColumnType("int");

                    b.Property<char>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<char>("Specailiztion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperenceYear = 3,
                            Name = "Marwan",
                            Specailiztion = "Football"
                        },
                        new
                        {
                            Id = 2,
                            ExperenceYear = 2,
                            Name = "Ibrahim",
                            Specailiztion = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            ExperenceYear = 2,
                            Name = "Hussien",
                            Specailiztion = "Basketball"
                        },
                        new
                        {
                            Id = 4,
                            ExperenceYear = 2,
                            Name = "Saif",
                            Specailiztion = "Football"
                        });
                });

            modelBuilder.Entity("Assement.Models.Competion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("competions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mansoura",
                            Title = "Chimp"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Paris",
                            Title = "Chimp"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Soudi Arabia",
                            Title = "Chimp"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mansoura",
                            Title = "Chimp"
                        });
                });

            modelBuilder.Entity("Assement.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Postion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salah",
                            Postion = "Goalkeeper",
                            TeamId = 1,
                            age = 22
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moody Amin",
                            Postion = "Goalkeeper",
                            TeamId = 1,
                            age = 32
                        },
                        new
                        {
                            Id = 3,
                            Name = "Messi",
                            Postion = "Striker",
                            TeamId = 2,
                            age = 32
                        },
                        new
                        {
                            Id = 4,
                            Name = "Popa",
                            Postion = "Diffencer",
                            TeamId = 3,
                            age = 32
                        });
                });

            modelBuilder.Entity("Assement.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cairo",
                            CoachId = 1,
                            Name = "AlAhly"
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            CoachId = 2,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cairo",
                            CoachId = 3,
                            Name = "Pyramids"
                        });
                });

            modelBuilder.Entity("CompetionTeam", b =>
                {
                    b.Property<int>("CompetionsId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("CompetionsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("CompetionTeam");
                });

            modelBuilder.Entity("Assement.Models.Player", b =>
                {
                    b.HasOne("Assement.Models.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Assement.Models.Team", b =>
                {
                    b.HasOne("Assement.Models.Coach", "Coach")
                        .WithOne("Team")
                        .HasForeignKey("Assement.Models.Team", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CompetionTeam", b =>
                {
                    b.HasOne("Assement.Models.Competion", null)
                        .WithMany()
                        .HasForeignKey("CompetionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assement.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assement.Models.Coach", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("Assement.Models.Team", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
